name: 'Run CI Dart no setup'
description: 'Run ci. Reusable across dart and flutter repositories once dart or flutter is set up.'

runs:
  using: 'composite'
  steps:
    - name: Setup dev_build
      shell: bash
      run: dart pub global activate dev_build
    - name: Run ci
      shell: bash
      run: dart pub global run dev_build:run_ci --recursive

