name: tekartik_ci_support
description: An example support project.
publish_to: none
version: 0.1.0
# homepage: https://www.example.com
#

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_ci:
    git:
      url: https://github.com/tekartik/ci.dart
      path: ci
  process_run: ">=1.2.1+1"
  path: ">=1.9.0"
dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints


resolution: workspace
