name: tekartik_ci_support
description: An example support project.
publish_to: none
# version: 1.0.0
# homepage: https://www.example.com
#

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  tekartik_ci:
    git:
      url: git://github.com/tekartik/ci.dart
      ref: dart2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2

dependency_overrides:
  tekartik_ci:
    path: ../ci
