name: tekartik_ci_support
description: An example support project.
publish_to: none
version: 0.1.0
# homepage: https://www.example.com
#

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_ci:
    git:
      url: https://github.com/tekartik/ci.dart
      ref: dart3a
      path: ci
  process_run:
  path:
dev_dependencies:
  lints: '>=1.0.0'
  test: ">=1.6.0"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints


resolution: workspace
