name: tekartik_ci_support
description: An example support project.
publish_to: none
# version: 1.0.0
# homepage: https://www.example.com
#

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tekartik_ci:
    git:
      url: https://github.com/tekartik/ci.dart
      ref: dart2_3

dev_dependencies:
  lints: '>=1.0.0'
  test: ^1.6.0
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3

dependency_overrides:
  tekartik_ci:
    path: ../ci
