name: tekartik_ci
description: Tekartik CI helpers for dart
version: 0.1.0
publish_to: none
# homepage: https://www.example.com
#

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  meta:
  path: ^1.6.0
  process_run: '>=0.10.4+1'
  io:
  pub_semver:
dev_dependencies:
  lints: '>=1.0.0'
  test: ^1.6.0