name: tekartik_ci
description: Tekartik CI helpers for dart
version: 0.1.0
publish_to: none
# homepage: https://www.example.com
#

environment:
  sdk: ^3.9.0

dependencies:
  meta: ">=1.15.0"
  path: ">=1.9.0"
  process_run: ">=1.2.1+1"
  dev_build: ">=1.1.2"
  io:
  pub_semver: ">=2.1.4"
dev_dependencies:
  lints: '>=5.0.0'
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
  test: ">=1.24.0"
executables:
  setup_sqlite3lib:
  setup_portaudiolib:
resolution: workspace
