name: ci_repo_support
description: Ci repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  path:
  pub_semver:
  tekartik_travis_ci_flutter:
    git:
      url: https://github.com/tekartik/travis_ci_flutter.dart
      ref: dart3a
    version: '>=0.1.0'
  process_run: '>=0.10.3'
  test:
  dev_build:
  lints: '>=1.0.0'

