name: ci_repo_support
description: Ci repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.9.0

dev_dependencies:
  path: ">=1.9.0"
  pub_semver: ">=2.1.4"
  tekartik_travis_ci_flutter:
    git:
      url: https://github.com/tekartik/travis_ci_flutter.dart
    version: '>=0.1.0'
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  lints: ">=5.0.0"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
resolution: workspace

