name: Run CI workflow local flutter default
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # every sunday at midnight

jobs:
  ci:
    name: Run ci
    uses: ./.github/workflows/run_ci_flutter_jobs.yml
