name: Run CI workflow local dart default
on:
  push:
    branches: ['**'] # Not on tag pushes
    paths-ignore: ['**.md'] # Not on doc only changes
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # every sunday at midnight

jobs:
  ci:
    name: Run ci
    uses: ./.github/workflows/run_ci_dart_jobs.yml
