name: Run CI dart
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # every sunday at midnight

jobs:
  test:
    name: Test on ${{ matrix.os }} / dart ${{ matrix.dart }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: repo_support
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            dart: stable
          - os: ubuntu-latest
            dart: beta
          - os: ubuntu-latest
            dart: dev
          - os: windows-latest
            dart: stable
          - os: macos-latest
            dart: stable
    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1.4
        with:
          sdk: ${{ matrix.dart }}
      - run: dart --version
      - name: Install libsqlite3
        run: |
          dart pub global activate --source git https://github.com/tekartik/ci.dart --git-path ci --git-ref dart3a
          dart pub global run tekartik_ci:setup_sqlite3lib
      - name: Install libportaudio
        run: |
          dart pub global activate --source git https://github.com/tekartik/ci.dart --git-path ci --git-ref dart3a
          dart pub global run tekartik_ci:setup_portaudiolib
      - run: dart pub get
      - run: dart run tool/run_ci.dart
